# Site settings
title: "Stat 355 Final"
description: "A website of my financial data analysis"
url: "https://arthurjohnson2026.github.io/statsfinal.github.io/"  # Replace with your GitHub Pages URL
author: Arthur Johnson  # Your name

# Theme settings
theme: minima # You can replace this with other supported GitHub Pages themes like jekyll-theme-cayman, slate, etc.

header_pages:
  - data.md
  - methodology.md
  - results.md
  - conclusions.md
  
# Optional plugins
plugins:
  - jekyll-feed  # This plugin adds an RSS feed to your site
  - jekyll-seo-tag  # Adds SEO optimization tags to your site
  - jekyll-sitemap  # Automatically generates a sitemap



# Markdown settings
markdown: kramdown  # Default for GitHub Pages
highlighter: rouge  # Syntax highlighting for code blocks

# Build settings (optional)
future: true  # Show future-dated posts
